Web/Models/ErrorViewModel.cs
using System;

namespace Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web/Controllers/DownloadController.cs
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Web.Services;

namespace Web.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class DownloadController : ControllerBase
    {
        private readonly IFileStorageService fileStorageService;

        public DownloadController(IFileStorageService fileStorageService)
        {
            this.fileStorageService = fileStorageService;
        }

        public async Task<IActionResult> GetFile(string fileName)
        {
            var filePath = Path.Combine("Files", fileName);
            if (!await fileStorageService.ExistsAsync(filePath))
            {
                return NotFound();
            }

            var fileStream = await fileStorageService.GetFileAsync(filePath);
            var file = ReadFully(fileStream);
            return new FileContentResult(file, "application/octet-stream")
            {
                FileDownloadName = fileName
            };
        }

        // https://stackoverflow.com/a/221941
        private static byte[] ReadFully(Stream input)
        {
            input.Position = 0;
            byte[] buffer = new byte[16 * 1024];
            using (MemoryStream ms = new MemoryStream())
            {
                int read;
                while ((read = input.Read(buffer, 0, buffer.Length)) > 0)
                {
                    ms.Write(buffer, 0, read);
                }
                return ms.ToArray();
            }
        }
    }
}

Web/Controllers/HomeController.cs
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Web.Models;
using Web.Services;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IFileStorageService fileStorageService;

        public HomeController(IFileStorageService fileStorageService)
        {
            this.fileStorageService = fileStorageService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<ViewResult> Files()
        {
            var files = await fileStorageService.EnumerateFilesAsync("Files");
            return View(files.ToArray());
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web/Views/Home/Files.cshtml
@model string[]
@{
    ViewData["Title"] = "Files";
}

<h1>Files</h1>

@if(Model.Length == 0)
{
    <p>No files!</p>
}
else
{
    <ul>
    @foreach(var file in Model)
    {
        <li><a class="nav-link text-dark" asp-area="" asp-controller="Download" asp-action="GetFile" asp-route-fileName="@file.Replace("Files/", "")">@file.Replace("Files/", "")</a></li>
    }
    </ul>
}

Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@inject Web.Services.ITimeService timeService

<div class="text-center">
    <h1 class="display-4">Welcome to .NET Modernization Day</h1>
    <p>Local time is @timeService.GetCurrentTime()</p>
    <p>UTC time is @DateTime.UtcNow</p>
</div>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Files">Files</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>